### ISSUE TITLE
Update to SDK 2 - Homey v5 support

### ISSUE THREAD

**Issue by stefan-lindvall** [kerkenit/nl.kerkenit.christiandates#3]
Hi, do you plan to update this app to SDK 2 and Homey v5 support?

**Comment by kerkenit** [comment]
No not in the moment. I don't trust the software quality of Athom. I'm at version 4.2.0 and it just works right now.
I don't want to update because my experience is they will break it (again?).
Whit this said, I don't use my Homey that much. I'm moved everything away except the 433Mhz and ZWave. All app updates are off, so mine is in stable mode. 
> Never change a winning theme.
Sorry, I wish my experience with Homey where better, but in my opinion the software quality and the support are very bad.
